-- Script for setting up Oracle DB tables and stored procedures for Mbr.Api.Workflow.FinalizedBill

-- Table for audit logs
CREATE TABLE finalizedbill_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mic_bill_id VARCHAR2(255),
    correlation_id VARCHAR2(255),
    payload CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for exception logs
CREATE TABLE finalizedbill_exceptions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mic_bill_id VARCHAR2(255),
    correlation_id VARCHAR2(255),
    exception_message VARCHAR2(4000),
    stack_trace CLOB,
    context VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stored procedure for inserting audit logs
CREATE OR REPLACE PROCEDURE ADD_AUDIT_LOG (
    p_mic_bill_id IN VARCHAR2,
    p_correlation_id IN VARCHAR2,
    p_payload IN CLOB
) AS
BEGIN
    INSERT INTO finalizedbill_logs (mic_bill_id, correlation_id, payload)
    VALUES (p_mic_bill_id, p_correlation_id, p_payload);
    COMMIT;
END ADD_AUDIT_LOG;
/

-- Stored procedure for inserting exception logs
CREATE OR REPLACE PROCEDURE ADD_EXCEPTION_LOG (
    p_mic_bill_id IN VARCHAR2,
    p_correlation_id IN VARCHAR2,
    p_exception_message IN VARCHAR2,
    p_stack_trace IN CLOB,
    p_context IN VARCHAR2
) AS
BEGIN
    INSERT INTO finalizedbill_exceptions (mic_bill_id, correlation_id, exception_message, stack_trace, context)
    VALUES (p_mic_bill_id, p_correlation_id, p_exception_message, p_stack_trace, p_context);
    COMMIT;
END ADD_EXCEPTION_LOG;
/
